name: Start Release
on:
  workflow_dispatch:
    inputs:
      release-number:
        description: 'Semantic version with format major.minor.patch (for example 4.2.0)'
        type: string
        required: true
      start-point:
        description: 'Starting point of the release. Can be a SHA, a branch or a tag. Default is origin/develop'
        type: string
        default: 'develop'

jobs:
  release:
    runs-on: [unity-linux-runner]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Display inputs
        run: |
          echo ${{ inputs.release-number }}
          echo ${{ inputs.start-point }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Checkout
        uses: actions/checkout@v6
        id: checkout
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: '${{ inputs.start-point }}'

      - name: Release branch creation
        env:
          RELEASE_SEMVER: ${{ inputs.release-number }}
        run: |
          release_branch="release/$RELEASE_SEMVER"
          git branch "$release_branch"
          git push -u origin "$release_branch"

      - name: Working branch creation
        env:
          RELEASE_SEMVER: ${{ inputs.release-number }}
        run: |
          working_branch="release/${RELEASE_SEMVER}-working"
          git branch "$working_branch"
          dotnet run --file Tools/scripts/changelog.cs -- release $RELEASE_SEMVER -i "$(pwd)/Packages/com.unity.cloud.gltfast/CHANGELOG.md"
          Tools/scripts/release-start.sh $RELEASE_SEMVER
          dotnet run --file Tools/scripts/changelog.cs -- info -i "$(pwd)/Packages/com.unity.cloud.gltfast/CHANGELOG.md" > .tmp-git-pull-request-body.md

      - name: Create Pr
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          title: "[Automated] Release ${{inputs.release-number}}"
          branch: "release/${{ inputs.release-number }}-working"
          base: "release/${{inputs.release-number}}"
          commit-message: "Release ${{inputs.release-number}}"
          body-path: .tmp-git-pull-request-body.md
          reviewers: |
            andreas-atteneder
          labels: |
            automated pr
            release
          delete-branch: true
